project: 
  type: website
  
website:
  title: "2025_DAIE_ICA_2_BF"
  navbar:
    left:
        - text: "Home"
          href: index.qmd
        - text: "Interactive Dashboard"
          href: app.html      

format: 
  html:
    theme: flatly



