---
title: "2025_DAIE_ICA_2_BF"
format: dashboard
server: shiny
page-layout: full
theme: flatly
---


```{r}
#| label: Install and Load Libraries
#| message: true
#| warning: true
#| include: false

if(!require("shiny"))
  install.packages("shiny")
  library(shiny)

if(!require("DT"))
  install.packages("DT")
  library(DT)

if(!require("DBI"))
  install.packages("DBI")
  library(DBI)

if(!require("RSQLite"))
  install.packages("RSQLite")
  library(RSQLite)

if(!require("ggplot2"))
  install.packages("ggplot2")
  library(ggplot2)

if(!require("plotly"))
  install.packages("plotly")
  library(plotly)

if(!require("dplyr"))
  install.packages("dplyr")
  library(dplyr)

conn <- dbConnect(RSQLite::SQLite(), "virtual_production.db")
dbListTables(conn)

```

```{r}
#| label: Data View UI
#| echo: false
#| message: true
#| warning: true
 
ui <- tabsetPanel(
  tabPanel("Data View",
  selectInput("table_select", "Select a Table to View:",
  choices = c("Clients", "Productions", "CrewMembers", "Assets")),
  DTOutput("table_output")))


```

```{r}
#| label: Server
#| echo: false
#| message: true
#| warning: true


server <-  output$table_output <- renderDT({
    req(input$table_select)
    df <- dbReadTable(conn, input$table_select)
    datatable(df, options = list(pageLength = 10, scrollX = TRUE))
  })
```


```{r}
#| label: Run Shiny App
#| message: true
#| warning: true

shinyApp(ui, server)

```


